### ISSUE TITLE
Trigger encrypted config correctly

### ISSUE THREAD

**Issue by Leont** [skaji/perl6-CPAN-Uploader-Tiny#3]
The current logic doesn't appear to try to read an encrypted configuration file, except when the file couldn't be opened. Instead it should search for a `----BEGIN PGP MESSAGE----` (or check for it being a binary file) and trigger on that.

**Comment by skaji** [comment]
`try $file.IO.slurp(:!bin)` try to check whether it is a binary file or not :)

Yeah, I will search for a `----BEGIN PGP MESSAGE----` too.

**Comment by Leont** [comment]
Thanks!
